version : '3'

services:
    rds:
        image: redis
    server1:
        image: server
        depends_on:
          - rds        
        environment:
            - SERVERID=1
            - PORT=8080
        volumes:
            - ./app:/home/node/app/src/
    server2:
        image: server
        depends_on:
          - rds
        environment:
            - SERVERID=2
            - PORT=8080    
        volumes:
            - ./app:/home/node/app/src/
    server3:
        image: server
        depends_on:
          - rds
        environment:
            - SERVERID=3
            - PORT=8080    
        volumes:
            - ./app:/home/node/app/src/    
    onlineCounter:
        image: server
        depends_on:
            - rds        
        volumes:
            - ./online_counter:/home/node/app/src/
    lb:
        image: haproxy
        depends_on:
            - server1
            - server2            
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy    